# Generated by Django 3.0 on 2022-09-23 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_auto_20220923_0354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='commenter',
        ),
    ]
